/**
 * GENERATED. The Italian mail strings, bought by
 * `pnpm translate:mail --locale it` on 2026-09-14 from
 * `src/mail/memory/it.json` (model: google/gemini-3.8-flash).
 *
 * DO NOT EDIT THIS FILE. The next run rebuilds it from the English in
 * `strings.ts` and the memory, memory first, and puts any hand edit back.
 * To change a sentence, edit its entry in the memory (find it by the `path`
 * field), or delete the entry and re-run to buy that one string again.
 *
 * The key order is the English dictionary's, so a diff shows changed values
 * and nothing else. `satisfies MailStrings` is what makes a key the generator
 * dropped a compile error rather than a letter missing a paragraph.
 */
import type { MailStrings } from './strings.js';

export const MAIL_STRINGS_IT = {
  invite: {
    subject: 'Il tuo invito a openplate',
    greeting: 'Ciao,',
    invited: 'Hai un invito per openplate, un diario alimentare che conserva i tuoi dati sul tuo dispositivo.',
    open: 'Apri questo link sul dispositivo su cui vuoi usare openplate:',
    expiry: 'Il link funziona una sola volta e scade il {date}.',
    password:
      'In quella pagina puoi scegliere una password. Da quel momento in poi potrai accedere con il tuo indirizzo email e questa password, su qualsiasi dispositivo.',
    help: "Se il link non funziona più, chiedine uno nuovo a chi ti ha inviato l'invito.",
  },
  reset: {
    subject: 'Imposta una nuova password per openplate',
    greeting: 'Ciao,',
    intro: "Qualcuno ha chiesto una nuova password per l'account openplate associato a questo indirizzo email.",
    open: 'Apri questo link e scegli una nuova password:',
    expiry: "Il link funziona una sola volta e scade tra un'ora.",
    ignore: 'Se non sei tu ad averlo richiesto, puoi ignorare questa email. La tua password non verrà modificata.',
    help: 'Se il link non funziona più, richiedine uno nuovo nella pagina di accesso.',
  },
  accountNotice: {
    subject: 'Hai già un account openplate',
    greeting: 'Ciao,',
    invited:
      "Qualcuno ti ha inviato un invito per openplate usando questo indirizzo email. Hai già un account, quindi l'invito non è stato inviato.",
    signIn: 'Accedi con questo indirizzo email e la tua password.',
    forgotten: 'Se hai dimenticato la password, richiedine una nuova nella pagina di accesso.',
  },
} satisfies MailStrings;
