/**
 * GENERATED. The Turkish mail strings, bought by
 * `pnpm translate:mail --locale tr` on 2026-09-14 from
 * `src/mail/memory/tr.json` (model: google/gemini-3.8-flash).
 *
 * DO NOT EDIT THIS FILE. The next run rebuilds it from the English in
 * `strings.ts` and the memory, memory first, and puts any hand edit back.
 * To change a sentence, edit its entry in the memory (find it by the `path`
 * field), or delete the entry and re-run to buy that one string again.
 *
 * The key order is the English dictionary's, so a diff shows changed values
 * and nothing else. `satisfies MailStrings` is what makes a key the generator
 * dropped a compile error rather than a letter missing a paragraph.
 */
import type { MailStrings } from './strings.js';

export const MAIL_STRINGS_TR = {
  invite: {
    subject: 'openplate davetin',
    greeting: 'Merhaba,',
    invited: 'Verilerini kendi cihazında tutan bir yemek günlüğü olan openplate uygulamasına davet edildin.',
    open: 'openplate uygulamasını kullanmak istediğin cihazda bu bağlantıyı aç:',
    expiry: 'Bağlantı yalnızca bir kez çalışır ve süresi {date} tarihinde dolar.',
    password:
      'O sayfada bir şifre belirlersin. Bundan sonra herhangi bir cihazda e-posta adresin ve bu şifreyle giriş yaparsın.',
    help: 'Bağlantı artık çalışmıyorsa, sana gönderen kişiden yeni bir bağlantı iste.',
  },
  reset: {
    subject: 'Yeni bir openplate şifresi belirle',
    greeting: 'Merhaba,',
    intro: 'Biri bu e-posta adresine bağlı openplate hesabı için yeni bir şifre istedi.',
    open: 'Bu bağlantıyı aç ve yeni bir şifre belirle:',
    expiry: 'Bağlantı yalnızca bir kez çalışır ve süresi bir saat içinde dolar.',
    ignore: 'Bunu sen istemediysen bu e-postayı görmezden gelebilirsin. Şifren olduğu gibi kalır.',
    help: 'Bağlantı artık çalışmıyorsa, giriş sayfasından yeni bir tane iste.',
  },
  accountNotice: {
    subject: 'Zaten bir openplate hesabın var',
    greeting: 'Merhaba,',
    invited:
      'Biri bu e-posta adresini kullanarak seni openplate uygulamasına davet etti. Zaten bir hesabın var, bu yüzden davet gönderilmedi.',
    signIn: 'Bu e-posta adresi ve şifrenle giriş yap.',
    forgotten: 'Şifreni unuttuysan, giriş sayfasından yeni bir şifre iste.',
  },
} satisfies MailStrings;
