/**
 * GENERATED. The French mail strings, bought by
 * `pnpm translate:mail --locale fr` on 2026-09-14 from
 * `src/mail/memory/fr.json` (model: google/gemini-3.8-flash).
 *
 * DO NOT EDIT THIS FILE. The next run rebuilds it from the English in
 * `strings.ts` and the memory, memory first, and puts any hand edit back.
 * To change a sentence, edit its entry in the memory (find it by the `path`
 * field), or delete the entry and re-run to buy that one string again.
 *
 * The key order is the English dictionary's, so a diff shows changed values
 * and nothing else. `satisfies MailStrings` is what makes a key the generator
 * dropped a compile error rather than a letter missing a paragraph.
 */
import type { MailStrings } from './strings.js';

export const MAIL_STRINGS_FR = {
  invite: {
    subject: 'Ton invitation à openplate',
    greeting: 'Bonjour,',
    invited: 'Tu es invité sur openplate, un journal alimentaire qui garde tes données sur ton propre appareil.',
    open: "Ouvre ce lien sur l'appareil où tu souhaites utiliser openplate :",
    expiry: "Le lien ne fonctionne qu'une seule fois, et il expire le {date}.",
    password:
      "Sur cette page, tu choisis un mot de passe. Ensuite, tu te connectes avec ton adresse e-mail et ce mot de passe, sur n'importe quel appareil.",
    help: "Si le lien ne fonctionne plus, demande un nouveau lien à la personne qui te l'a envoyé.",
  },
  reset: {
    subject: 'Définir un nouveau mot de passe openplate',
    greeting: 'Bonjour,',
    intro: "Quelqu'un a demandé un nouveau mot de passe pour le compte openplate lié à cette adresse e-mail.",
    open: 'Ouvre ce lien et choisis un nouveau mot de passe :',
    expiry: "Le lien ne fonctionne qu'une seule fois, et il expire dans une heure.",
    ignore: "Si tu n'as rien demandé, tu peux ignorer cet e-mail. Ton mot de passe reste inchangé.",
    help: 'Si le lien ne fonctionne plus, demandes-en un nouveau sur la page de connexion.',
  },
  accountNotice: {
    subject: 'Tu as déjà un compte openplate',
    greeting: 'Bonjour,',
    invited:
      "Quelqu'un t'a invité sur openplate avec cette adresse e-mail. Tu as déjà un compte, donc aucune invitation n'a été envoyée.",
    signIn: 'Connecte-toi avec cette adresse e-mail et ton mot de passe.',
    forgotten: 'Si tu as oublié ton mot de passe, demandes-en un nouveau sur la page de connexion.',
  },
} satisfies MailStrings;
