/**
 * GENERATED. The Spanish mail strings, bought by
 * `pnpm translate:mail --locale es` on 2026-09-14 from
 * `src/mail/memory/es.json` (model: google/gemini-3.8-flash).
 *
 * DO NOT EDIT THIS FILE. The next run rebuilds it from the English in
 * `strings.ts` and the memory, memory first, and puts any hand edit back.
 * To change a sentence, edit its entry in the memory (find it by the `path`
 * field), or delete the entry and re-run to buy that one string again.
 *
 * The key order is the English dictionary's, so a diff shows changed values
 * and nothing else. `satisfies MailStrings` is what makes a key the generator
 * dropped a compile error rather than a letter missing a paragraph.
 */
import type { MailStrings } from './strings.js';

export const MAIL_STRINGS_ES = {
  invite: {
    subject: 'Tu invitación a openplate',
    greeting: 'Hola:',
    invited: 'Te damos la bienvenida a openplate, un diario de comida que guarda tus datos en tu propio dispositivo.',
    open: 'Abre este enlace en el dispositivo donde quieras usar openplate:',
    expiry: 'El enlace funciona una sola vez y caduca el {date}.',
    password:
      'En esa página eliges una contraseña. A partir de entonces inicias sesión con tu correo electrónico y esa contraseña, en cualquier dispositivo.',
    help: 'Si el enlace ya no funciona, pídele uno nuevo a la persona que te lo envió.',
  },
  reset: {
    subject: 'Elige una contraseña nueva de openplate',
    greeting: 'Hola:',
    intro: 'Alguien ha solicitado una contraseña nueva para la cuenta de openplate asociada a este correo electrónico.',
    open: 'Abre este enlace y elige una contraseña nueva:',
    expiry: 'El enlace funciona una sola vez y caduca en una hora.',
    ignore: 'Si no lo has solicitado tú, puedes ignorar este mensaje. Tu contraseña no cambiará.',
    help: 'Si el enlace ya no funciona, solicita uno nuevo en la página de inicio de sesión.',
  },
  accountNotice: {
    subject: 'Ya tienes una cuenta de openplate',
    greeting: 'Hola:',
    invited:
      'Alguien te ha invitado a openplate con este correo electrónico. Ya tienes una cuenta, así que no se ha enviado ninguna invitación.',
    signIn: 'Inicia sesión con este correo electrónico y tu contraseña.',
    forgotten: 'Si has olvidado tu contraseña, solicita una nueva en la página de inicio de sesión.',
  },
} satisfies MailStrings;
