/**
 * Refreshes the vendored list of throwaway mail domains the open sign-up door
 * refuses (M253).
 *
 *   pnpm sync:disposable-domains              the newest commit on `main`
 *   pnpm sync:disposable-domains --sha <sha>  one named commit
 *
 * THE SOURCE is github.com/disposable-email-domains/disposable-email-domains,
 * `disposable_email_blocklist.conf`, released under CC0 1.0 (public domain
 * dedication), so the snapshot can live in this MIT repository with no notice
 * beyond the provenance header this script writes.
 *
 * NO RUNTIME FETCH, BY DESIGN. The service reads the committed module and
 * nothing else: a sign-up door that depended on GitHub being reachable would
 * be a door GitHub could close, and a list that changed under a running
 * process could not be reviewed. A refresh is this script, a diff, a commit.
 *
 * THE LIST IS FETCHED AT THE COMMIT IT NAMES, never at a branch, so the
 * header's commit is the commit the entries came from even if `main` moves
 * during the run.
 */
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const REPOSITORY = 'disposable-email-domains/disposable-email-domains';
const LIST_PATH = 'disposable_email_blocklist.conf';
const OUTPUT = fileURLToPath(new URL('../src/accounts/disposable-domains.generated.ts', import.meta.url));

/** A lowercase domain, the only shape an entry may have. Anything else fails the run rather than shipping. */
const DOMAIN_PATTERN = /^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)+$/;

/** The one field this script reads off the GitHub commit API. */
interface CommitAnswer {
  readonly sha?: unknown;
  readonly commit?: { readonly committer?: { readonly date?: unknown } };
}

function readShaArgument(argv: string[]): string | null {
  const index = argv.indexOf('--sha');
  if (index === -1) return null;
  const sha = argv[index + 1];
  if (sha === undefined || !/^[0-9a-f]{40}$/.test(sha)) throw new Error('--sha needs a full 40 character commit hash');
  return sha;
}

async function resolveCommit(requested: string | null): Promise<{ sha: string; date: string }> {
  const ref = requested ?? 'main';
  const response = await fetch(`https://api.github.com/repos/${REPOSITORY}/commits/${ref}`, {
    headers: { accept: 'application/vnd.github+json' },
  });
  if (!response.ok) throw new Error(`GitHub answered ${response.status} for the commit ${ref}`);
  const answer: CommitAnswer = Object(await response.json());
  const sha = String(answer.sha ?? '');
  const date = String(answer.commit?.committer?.date ?? '');
  if (!/^[0-9a-f]{40}$/.test(sha) || date === '') throw new Error('GitHub answered a commit with no sha or date');
  return { sha, date };
}

async function fetchDomains(sha: string): Promise<string[]> {
  const response = await fetch(`https://raw.githubusercontent.com/${REPOSITORY}/${sha}/${LIST_PATH}`);
  if (!response.ok) throw new Error(`GitHub answered ${response.status} for the list at ${sha}`);
  const lines = (await response.text()).split('\n').map((line) => line.trim().toLowerCase());
  const domains = [...new Set(lines.filter((line) => line !== '' && !line.startsWith('#')))].toSorted();
  const malformed = domains.filter((domain) => !DOMAIN_PATTERN.test(domain));
  if (malformed.length > 0) throw new Error(`the list carries entries that are not domains: ${malformed.join(', ')}`);
  // A floor, so a truncated download cannot ship as an almost empty list.
  if (domains.length < 1000) throw new Error(`the list has only ${domains.length} entries, refusing to write it`);
  return domains;
}

function render(input: { sha: string; date: string; domains: string[] }): string {
  const header = [
    '/**',
    ' * GENERATED by `scripts/sync-disposable-domains.ts`. Do not edit by hand:',
    ' * run `pnpm sync:disposable-domains` and commit the diff.',
    ' *',
    ` * Source: https://github.com/${REPOSITORY}/blob/${input.sha}/${LIST_PATH}`,
    ` * Commit: ${input.sha}`,
    ` * Committed: ${input.date}`,
    ' * License: CC0 1.0 Universal (public domain dedication).',
    ' *',
    ' * Throwaway mail domains the open sign-up door refuses. Read by',
    ' * `accounts/disposable-domains.ts`, which matches subdomains too.',
    ' */',
  ];
  const source = [
    'export const DISPOSABLE_DOMAINS_SOURCE = {',
    `  repository: '${REPOSITORY}',`,
    `  commit: '${input.sha}',`,
    `  committedAt: '${input.date}',`,
    '} as const;',
  ];
  const list = [
    'export const DISPOSABLE_DOMAINS: readonly string[] = [',
    ...input.domains.map((d) => `  '${d}',`),
    '];',
  ];
  return `${[...header, ...source, '', ...list].join('\n')}\n`;
}

async function main(): Promise<void> {
  const commit = await resolveCommit(readShaArgument(process.argv.slice(2)));
  const domains = await fetchDomains(commit.sha);
  await writeFile(OUTPUT, render({ ...commit, domains }), 'utf8');
  process.stdout.write(`Wrote ${domains.length} domains from ${commit.sha} to ${OUTPUT}\n`);
}

main().catch((cause: unknown) => {
  process.stderr.write(`${cause instanceof Error ? cause.message : 'the refresh failed'}\n`);
  process.exit(1);
});
