/**
 * The generated mail modules, against the memory that wrote them, M230 spec 03.
 *
 * `src/mail/strings.<lang>.ts` is written by `pnpm translate:mail` from the English in
 * `strings.ts` and `src/mail/memory/<lang>.json`, and by nothing else. A hand edit to a module is
 * put back by the next run; this is the check that finds the edit before that run does. It
 * rebuilds every generated module from the committed memory with the same function the script
 * uses and asserts the file on disk is that, byte for byte. The website proved its re-keyed UI
 * memory the same way in M230 spec 01.
 *
 * ── THE PLACEHOLDER CHECK IS THIS REPO'S, SO IT IS TESTED HERE ──
 * The library's token check knows `{{name}}`. A letter says `{date}`. `carriesPlaceholders` is
 * the one line that keeps a French invitation from losing its expiry, and it needs a case where
 * the lost placeholder is exactly the single-brace one.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { MAIL_STRINGS } from '../../src/mail/strings.js';
import { INSTANCE_LANGUAGES, type InstanceLanguage } from '../../src/protocol.js';
import { DASH, loadMemory, lookup } from '../../scripts/lib/translate.js';
import {
  GENERATED_LANGUAGES,
  HAND_WRITTEN_LANGUAGES,
  carriesPlaceholders,
  exportName,
  memoryFile,
  moduleFile,
  placeholderOffenders,
  placeholders,
  propertyLine,
  quote,
  renderModule,
  unitsOf,
} from '../../scripts/lib/translate-mail.js';

const ROOT = fileURLToPath(new URL('../..', import.meta.url));
const ENGLISH = MAIL_STRINGS.en;
const UNITS = unitsOf(ENGLISH);

/** The date a generated module's header carries, read the way the script reads it back. */
function headerDate(text: string): string {
  const date = /--locale \w+` on (\d{4}-\d{2}-\d{2})/.exec(text)?.[1];
  assert.ok(date !== undefined, 'a generated module names the day it was written');
  return date;
}

describe('the languages', () => {
  it('are the protocol list split into two hand-written and the rest generated', () => {
    assert.deepEqual([...HAND_WRITTEN_LANGUAGES].toSorted(), ['de', 'en']);
    assert.deepEqual(
      [...HAND_WRITTEN_LANGUAGES, ...GENERATED_LANGUAGES].toSorted(),
      [...INSTANCE_LANGUAGES].toSorted(),
    );
    assert.ok(GENERATED_LANGUAGES.length >= 4, 'four languages are bought today');
  });
});

describe('each generated module', () => {
  for (const language of GENERATED_LANGUAGES) {
    const file = resolve(ROOT, moduleFile(language));
    const text = readFileSync(file, 'utf8');
    const memory = loadMemory(resolve(ROOT, memoryFile(language)));
    const done = lookup(memory, language);

    it(`${language}: rebuilds byte for byte from the English and its memory`, () => {
      const models = [...new Set(UNITS.map((unit) => memory[unit.hash]?.model).filter((model) => model !== undefined))];
      const rebuilt = renderModule({
        english: ENGLISH,
        memory: done,
        provenance: { language, models, at: headerDate(text) },
      });
      assert.equal(
        text,
        rebuilt,
        `${moduleFile(language)} is not what its memory renders. It is not edited by hand: change the entry in ` +
          `${memoryFile(language)} and run \`pnpm translate:mail --locale ${language} --local\`.`,
      );
    });

    it(`${language}: its memory answers every English string, keyed by path`, () => {
      for (const unit of UNITS) {
        const entry = memory[unit.hash];
        assert.ok(entry !== undefined, `${language} memory has no entry for ${unit.key}`);
        assert.equal(entry.path, unit.key, 'the memo names the path it was bought under');
        assert.equal(entry.en, unit.source, 'the memo carries the English it answers');
        assert.ok(entry[language] !== undefined && entry[language] !== '', `${unit.key} has an empty answer`);
      }
    });

    it(`${language}: keeps every {placeholder} and carries no dash`, () => {
      assert.deepEqual(placeholderOffenders(UNITS, done), []);
      for (const [hash, entry] of Object.entries(memory)) {
        assert.ok(!DASH.test(entry[language] ?? ''), `${hash} carries a banned dash`);
      }
    });

    it(`${language}: says it is generated, imports only the type, and exports the name strings.ts folds in`, () => {
      assert.ok(text.startsWith('/**\n * GENERATED.'), 'the header opens by saying it is generated');
      assert.ok(text.includes('DO NOT EDIT THIS FILE'));
      assert.ok(text.includes(`pnpm translate:mail --locale ${language}`), 'the header says how it is regenerated');
      const imports = text.split('\n').filter((line) => line.startsWith('import '));
      assert.deepEqual(imports, ["import type { MailStrings } from './strings.js';"]);
      assert.ok(text.includes(`export const ${exportName(language)} = {`));
      assert.ok(text.trimEnd().endsWith('} satisfies MailStrings;'));
    });

    it(`${language}: is what MAIL_STRINGS carries for it`, () => {
      // The fold in `strings.ts` and the module on disk agree, so the letters the service sends
      // are the strings this test just proved came from the memory.
      for (const unit of UNITS) {
        const [letter, key] = unit.leaf.split('.');
        assert.ok(letter !== undefined && key !== undefined);
        const shipped = Object.entries(MAIL_STRINGS[language]).find(([name]) => name === letter)?.[1];
        assert.ok(shipped !== undefined, `${language} has no ${letter}`);
        assert.equal(Object.entries(shipped).find(([name]) => name === key)?.[1], done.get(unit.hash));
      }
    });
  }
});

describe('the rebuild proof would fail', () => {
  const language: InstanceLanguage = GENERATED_LANGUAGES[0] ?? 'fr';
  const text = readFileSync(resolve(ROOT, moduleFile(language)), 'utf8');
  const done = lookup(loadMemory(resolve(ROOT, memoryFile(language))), language);

  it('on one changed memory value', () => {
    const altered = new Map(done);
    const [hash] = altered.keys();
    assert.ok(hash !== undefined);
    altered.set(hash, `${altered.get(hash)} `);
    const rebuilt = renderModule({
      english: ENGLISH,
      memory: altered,
      provenance: { language, models: ['google/gemini-3.8-flash'], at: headerDate(text) },
    });
    assert.notEqual(rebuilt, text);
  });

  it('on a missing translation, by refusing to render at all', () => {
    const short = new Map(done);
    const [hash] = short.keys();
    assert.ok(hash !== undefined);
    short.delete(hash);
    assert.throws(
      () => renderModule({ english: ENGLISH, memory: short, provenance: { language, models: [], at: '2026-01-01' } }),
      /has no translation for mail:/,
    );
  });
});

describe('placeholders', () => {
  it('are the single-brace names fill() substitutes', () => {
    assert.deepEqual(placeholders('expires on {date}, see {date} and {other}'), ['{date}', '{date}', '{other}']);
    assert.deepEqual(placeholders('no placeholder here'), []);
  });

  it('may move and may not be lost, renamed, or invented', () => {
    assert.equal(carriesPlaceholders('expires on {date}.', 'Le {date}, il expire.'), true);
    assert.equal(carriesPlaceholders('expires on {date}.', 'Il expire le date.'), false);
    assert.equal(carriesPlaceholders('expires on {date}.', 'Il expire le {Datum}.'), false);
    assert.equal(carriesPlaceholders('expires soon.', 'Il expire le {date}.'), false);
    // The library's own token check sees double braces only, which is why this one exists.
    assert.equal(carriesPlaceholders('expires on {date}.', 'Il expire le {{date}}.'), false);
  });

  it('are reported by path with both strings', () => {
    const memory = new Map(UNITS.map((unit) => [unit.hash, unit.source] as const));
    const expiry = UNITS.find((unit) => unit.key === 'mail:invite.expiry');
    assert.ok(expiry !== undefined);
    memory.set(expiry.hash, 'The link expires on a date.');
    assert.deepEqual(placeholderOffenders(UNITS, memory), [
      { path: 'mail:invite.expiry', source: expiry.source, target: 'The link expires on a date.' },
    ]);
  });
});

describe('the rendering matches prettier', () => {
  it('quotes with single quotes unless the text has more of them', () => {
    assert.equal(quote('Bonjour,'), "'Bonjour,'");
    assert.equal(quote("l'appareil"), '"l\'appareil"');
    assert.equal(quote('say "hi"'), '\'say "hi"\'');
    assert.equal(quote(`it's "both"`), `'it\\'s "both"'`);
  });

  it('breaks a long value after the colon, one indent deeper', () => {
    assert.equal(propertyLine('    ', 'greeting', 'Hello,'), "    greeting: 'Hello,',");
    const long = 'x'.repeat(120);
    assert.equal(propertyLine('    ', 'password', long), `    password:\n      '${long}',`);
  });
});
